# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:        /blog/:title
relative_permalinks: false

# Setup
title:            Furkan Ayhan
tagline:          'Software Developer - Computer Engineer'
description:      'Furkan Ayhan - Software Developer - Ruby on Rails - Computer Engineer'
url:              https://www.furkanayhan.com
otherbaseurl:     /


# Analytics and webmaster tools stuff goes here
google_analytics:   UA-33612874-1
google_verify:      -yRZtByIj6h8B6bBEVBTPp_LTSXUcamiGYBX9Y_A374


author:
  name:           'Furkan ayhan'
  url:            https://www.furkanayhan.com

paginate:         5
paginate_path:    '/blog/page-:num/'

# Custom vars
version:          1.1.0

twitter_username:     furkanayhn
github_username:      furkanayhan
linkedin_username:    furkanayhan
google_plus_username: FurkanAyhan
facebook_username:    furkanayhn

gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-assets
  # - jekyll-archives

assets:
  cache: true
  js_compressor:  uglifier
  css_compressor: sass
